/**
 * Locale for testing tranformation of Angular locale into target locale.
 * Using some fantasy day and month names.
 */
const u = undefined;
function plural(val) {
  const n = val,
    i = Math.floor(Math.abs(val)),
    v = val.toString().replace(/^[^.]*\.?/, "").length;
  if (i === 1 && v === 0) return 1;
  return 5;
}
export default [
  "de",
  [["AM", "PM"], u, u],
  u,
  [
    ["R", "Z", "A", "C", "H", "S", "S"],
    ["Ra.", "Ze.", "Am.", "Co.", "Ha.", "Si.", "St."],
    [
      "Rainbowday",
      "Zenithday",
      "Amethyday",
      "Coolday",
      "Hailday",
      "Silverday",
      "Stormday",
    ],
    ["Ra.", "Ze.", "Am.", "Co.", "Ha.", "Si.", "St."],
  ],
  [
    ["R", "Z", "A", "C", "H", "S", "S"],
    ["Ra", "Ze", "Am", "Co", "Ha", "Si", "St"],
    [
      "Rainbowday",
      "Zenithday",
      "Amethyday",
      "Coolday",
      "Hailday",
      "Silverday",
      "Stormday",
    ],
    ["Ra.", "Ze.", "Am.", "Co.", "Ha.", "Si.", "St."],
  ],
  [
    ["F", "D", "W", "R", "P", "H", "F", "F", "L", "R", "S", "F"],
    [
      "Fro.",
      "Deep.",
      "Win.",
      "Rain.",
      "Pale.",
      "Hig.",
      "Firem.",
      "Firew.",
      "Low.",
      "Red.",
      "Snow.",
      "Fell.",
    ],
    [
      "Frostmoot",
      "Deepsnow",
      "Winterwane",
      "Rainmoot",
      "Palesun",
      "Highsun",
      "Firemoot",
      "Firewane",
      "Lowsun",
      "Redfall",
      "Snowmoot",
      "Fellnight",
    ],
  ],
  [
    ["F", "D", "W", "R", "P", "H", "F", "F", "L", "R", "S", "F"],
    [
      "Fro.",
      "Deep.",
      "Win.",
      "Rain.",
      "Pale.",
      "Hig.",
      "Firem.",
      "Firew.",
      "Low.",
      "Red.",
      "Snow.",
      "Fell.",
    ],
    [
      "Frostmoot",
      "Deepsnow",
      "Winterwane",
      "Rainmoot",
      "Palesun",
      "Highsun",
      "Firemoot",
      "Firewane",
      "Lowsun",
      "Redfall",
      "Snowmoot",
      "Fellnight",
    ],
  ],
  [["v. Chr.", "n. Chr."], u, u],
  1,
  [6, 0],
  ["dd.MM.yy", "dd.MM.y", "d. MMMM y", "EEEE, d. MMMM y"],
  ["HH:mm", "HH:mm:ss", "HH:mm:ss z", "HH:mm:ss zzzz"],
  ["{1}, {0}", u, "{1} 'um' {0}", u],
  [",", ".", ";", "%", "+", "-", "E", "·", "‰", "∞", "NaN", ":"],
  ["#,##0.###", "#,##0 %", "#,##0.00 ¤", "#E0"],
  "EUR",
  "€",
  "Euro",
  {
    ATS: ["öS"],
    AUD: ["AU$", "$"],
    BGM: ["BGK"],
    BGO: ["BGJ"],
    BYN: [u, "р."],
    CUC: [u, "Cub$"],
    DEM: ["DM"],
    FKP: [u, "Fl£"],
    GHS: [u, "₵"],
    GNF: [u, "F.G."],
    KMF: [u, "FC"],
    PHP: [u, "₱"],
    RON: [u, "L"],
    RUR: [u, "р."],
    RWF: [u, "F.Rw"],
    SYP: [],
    THB: ["฿"],
    TWD: ["NT$"],
    XXX: [],
    ZMW: [u, "K"],
  },
  "ltr",
  plural,
];
