// cypress static response keys, see packages/driver/src/cy/net-stubbing/static-response-utils.ts
export const STATIC_RESPONSE_KEYS = [
  "body",
  "fixture",
  "statusCode",
  "headers",
  "forceNetworkError",
  "throttleKbps",
  "delay",
  "delayMs",
];

export const HTTP_METHODS = [
  "ACL",
  "BIND",
  "CHECKOUT",
  "CONNECT",
  "COPY",
  "DELETE",
  "GET",
  "HEAD",
  "LINK",
  "LOCK",
  "M-SEARCH",
  "MERGE",
  "MKACTIVITY",
  "MKCALENDAR",
  "MKCOL",
  "MOVE",
  "NOTIFY",
  "OPTIONS",
  "PATCH",
  "POST",
  "PROPFIND",
  "PROPPATCH",
  "PURGE",
  "PUT",
  "REBIND",
  "REPORT",
  "SEARCH",
  "SOURCE",
  "SUBSCRIBE",
  "TRACE",
  "UNBIND",
  "UNLINK",
  "UNLOCK",
  "UNSUBSCRIBE",
];

export const STATIC_RESPONSE_WITH_OPTIONS_KEYS = [
  ...STATIC_RESPONSE_KEYS,
  "log",
];
